version: "3.8"

services:
  tinyproxy:
    build: ./tinyproxy
    container_name: tinyproxy
    environment:
      - PROXY_USER=${PROXY_USER}
      - PROXY_PASS=${PROXY_PASS}
      - TP_PORT=3128
      - TP_MAXCLIENTS=200
      - TP_TIMEOUT=600
      - EXTRA_CONNECT_PORTS=8443,9443,2053,2083,2087,2096
      - TZ=${TZ}
    expose:
      - "3128"
    restart: unless-stopped

  stunnel:
    build: ./stunnel
    container_name: stunnel443
    depends_on:
      - tinyproxy
    environment:
      - STUNNEL_BACKEND_HOST=tinyproxy
      - STUNNEL_BACKEND_PORT=3128
      - STUNNEL_ACCEPT_PORT=443
      - STUNNEL_CERT_FULLCHAIN=/certs/fullchain.pem
      - STUNNEL_CERT_PRIVKEY=/certs/privkey.pem
      - TZ=${TZ}
    ports:
      - "443:443"
    volumes:
      - ./certs:/certs:ro
    restart: unless-stopped

  acme:
    build: ./acme
    container_name: acme_certbotless
    environment:
      - ACME_DOMAIN=${ACME_DOMAIN}
      - ACME_EMAIL=${ACME_EMAIL}
      - ACME_STAGING=${ACME_STAGING}
      - TZ=${TZ}
    ports:
      - "80:80"
    volumes:
      - ./certs:/certs
      - acme_home:/acme.sh
    restart: unless-stopped

volumes:
  acme_home:
